### ISSUE TITLE
Safari Extension not working or works intermittently

### ISSUE THREAD

**Issue by GoogleCodeExporter** [daluu/autosmsclients#2]
```
What steps will reproduce the problem?
1. Send SMS from Safari extension

What is the expected output? What do you see instead?

A message sent message should be shown, but instead just keep getting message 
to enter correct CAPTCHA code when reattempt to send the message.

Appears to be an issue only with the Safari extension so far. Works fine with 
Chrome extension.


```

Original issue reported on code.google.com by `manga...@gmail.com` on 18 Sep 2011 at 2:05

**Comment by daluu** [comment]
This likely is problem with Safari limitation introduced since Safari 5.1, and thus the extension would work in Safari 5.0 but not higher versions, although I don't have the specific versions to confirm this. Per this thread:

https://devforums.apple.com/message/464397#464397

**Comment by daluu** [comment]
Fixable with Safari settings. Set Safari preferences > Privacy > Block cookies and other website data to "Never". Then may likely require a Safari restart (close and reopen).

If the cookie blocking setting is any other setting, the extension will fail to send the SMS. Tested on Safari 7.0.6
